import type { LyricsSong } from "./types";

const lyrics: LyricsSong = {
  title: "廃墟のソファ (Haikyou No Sofa)",
  jp: [
    "ここは雨の町かつては栄えた伝説の港町",
    "今では廃墟が立ち並び小銭をせがむ者が溢れ",
    "肌色ちがう学生が暮らす一軒の家に住み着いて半年ばかり経ったある雨の日",
    "しつこい鐘の音に起こされ歩いた",
    "石畳の通りで二人を見つける",
    "-----------------------------",
    "Walking in the rain I've been told today",
    "Never wanna see you again",
    "I feel like I'm still wet in this tiny room",
    "Why should I pretend to be high",
    "I walk to Green Fish to listen to the sound of silence",
    "A man who plays the harp gently shakes my hand",
    "And he leads me in to the story of him",
    "-----------------------------",
    "聞きたい曲も見つからず向かった先は町外れのcafe",
    "スープの匂いにケルトの音色に冷えた僕の心は溶け出す",
    "丸みを帯びたハーブ弾きの老人の話に何度救われるのだろう",
    "テーブルの上の新聞の見出しがなんとなく外を映し出すけど",
    "-----------------------------",
    "I see you shouting and yelling and struggling",
    "But I can't hear your voice",
    "I see you shouting and yelling and struggling",
    "But I can't feel the same",
    "-----------------------------",
    "ここは雨の町かつては栄えた伝説の石の町",
    "今では廃墟が立ち並び小銭をせがむ者が溢れ",
    "もしも神がいるならばこの地に姿をみせなよ",
  ],
  romaji: [
    "Koko wa ame no machi katsute wa sakaeta densetsu no minatomachi",
    "Ima de wa haikyo ga tachinarabi kozeni wo segamu mono ga afure",
    "Hadairo chigau gakusei ga kurasu ikken no ie ni",
    "Sumitsuite hantoshi bakari tatta aru ame no hi",
    "Shitsukoi kane no oto ni okosare aruita",
    "Ijidatami no toori de futari wo mitsukeru",
    "-----------------------------",
    "Walking in the rain I've been told today",
    "Never wanna see you again",
    "I feel like I'm still wet in this tiny room",
    "Why should I pretend to be high",
    "I walk to Green Fish to listen to the sound of silence",
    "A man who plays the harp gently shakes my hand",
    "And he leads me in to the story of him",
    "-----------------------------",
    "Kikitai kyoku mo mitsukarazu mukatta saki wa machihazure no cafe",
    "SUUPU no nioi ni KERUTO no neiro ni hieta boku no kokoro wa tokedasu",
    "Marumi wo obita HAABU hiki no roujin no hanashi ni nando sukuwareru no darou",
    "TEEBURU no ue no shinbun no midashi ga nanto naku soto wo utsushidasu kedo",
    "-----------------------------",
    "I see you shouting and yelling and struggling",
    "But I can't hear your voice",
    "I see you shouting and yelling and struggling",
    "But I can't feel the same",
    "-----------------------------",
    "Koko wa ame no machi katsute wa sakaeta densetsu no ishi no machi",
    "Ima de wa haikyo ga tachinarabi kozeni wo segamu mono ga afure",
    "Moshimo kami ga iru naraba kono chi ni sugata wo misena yo",
  ],
};

export default lyrics;
