import type { LyricsSong } from "./types";

const itsuka: LyricsSong = {
  title: "いつか (itsuka)",
  jp: [
    "少しずつ街の",
    "風も冷たくなってきたから",
    "風邪をひきやすい",
    "あなたの事が気になります",
    "冬の匂いが僕を通り抜け始めると",
    "溢(あふ)れる程",
    "切なくて逢いたくて…",
    "-----------------------------",
    "傷つきながらもがきながら",
    "僕達は明日という日を",
    "夢見て 生きていく",
    "-----------------------------",
    "いつか又どうしようもなく",
    "寂(さび)しくなったその時は",
    "何処(どこ)にいても",
    "何をしてても",
    "駆けつけてあげるから",
    "ありふれてる言葉なんて",
    "捨て去ってしまおう",
    "何も要らないあなたがいる",
    "それだけが僕の全て",
    "-----------------------------",
    "今年は雪が降るのかな?",
    "びしょ濡れになって",
    "はしゃいだあの日",
    "降り積もった真白な雪は",
    "全ての事を包み込んで行くだろう",
    "-----------------------------",
    "戸惑いながらつまずきながら",
    "僕達は昨日という日を",
    "かみしめて 歩いてく",
    "-----------------------------",
    "いつか又どうしようもなく",
    "寂(さび)しくなったその時は",
    "何処(どこ)にいても",
    "何をしてても",
    "駆けつけてあげるから",
    "ありふれてる言葉なんて",
    "捨て去ってしまおう",
    "何も要らないあなたがいる",
    "それだけが僕の全て",
    "-----------------------------",
    "大事なことをごまかしながら",
    "誰もが目をつぶり",
    "一人ぼっちになりそうになっても",
    "もう大丈夫だから",
    "-----------------------------",
    "いつか又大きな波が",
    "あなたを連れ去ろうとしても",
    "全ての力使い果たし",
    "守ってあげるから",
    "時間は過ぎ 人は流れ",
    "何もかも見えなくなっても",
    "ここに居るすぐ傍(そば)に",
    "それだけが僕の全て",
    "-----------------------------",
    "不安を抱(いだ)き",
    "悲しみに打たれ",
    "信じる事に挫(くじ)けそうになっても",
    "あなたを想い唄い続けて行く",
    "それだけが",
    "-----------------------------",
    "僕の全て",
  ],
  furigana: [
    "少（すこ）しずつ街（まち）の",
    "風（かぜ）も冷（つめ）たくなってきたから",
    "風邪（かぜ）をひきやすい",
    "あなたの事（こと）が気（き）になります",
    "冬（ふゆ）の匂（にお）いが僕（ぼく）を通（とお）り抜（ぬ）け始（はじ）めると",
    "溢（あふ）れる程（ほど）",
    "切（せつ）なくて逢（あ）いたくて…",
    "-----------------------------",
    "傷（きず）つきながらもがきながら",
    "僕達（ぼくたち）は明日（あした）という日（ひ）を",
    "夢見（ゆめみ）て 生（い）きていく",
    "-----------------------------",
    "いつか又（また）どうしようもなく",
    "寂（さび）しくなったその時（とき）は",
    "何処（どこ）にいても",
    "何（なに）をしてても",
    "駆（か）けつけてあげるから",
    "ありふれてる言葉（ことば）なんて",
    "捨（す）て去（さ）ってしまおう",
    "何（なに）も要（い）らないあなたがいる",
    "それだけが僕（ぼく）の全（すべ）て",
    "-----------------------------",
    "今年（ことし）は雪（ゆき）が降（ふ）るのかな?",
    "びしょ濡（ぬ）れになって",
    "はしゃいだあの日（ひ）",
    "降（ふ）り積（つ）もった真白（ましろ）な雪（ゆき）は",
    "全（すべ）ての事（こと）を包（つつ）み込（こ）んで行（い）くだろう",
    "-----------------------------",
    "戸惑（とまど）いながらつまずきながら",
    "僕達（ぼくたち）は昨日（きのう）という日（ひ）を",
    "かみしめて 歩（ある）いてく",
    "-----------------------------",
    "いつか又（また）どうしようもなく",
    "寂（さび）しくなったその時（とき）は",
    "何処（どこ）にいても",
    "何（なに）をしてても",
    "駆（か）けつけてあげるから",
    "ありふれてる言葉（ことば）なんて",
    "捨（す）て去（さ）ってしまおう",
    "何（なに）も要（い）らないあなたがいる",
    "それだけが僕（ぼく）の全（すべ）て",
    "-----------------------------",
    "大事（だいじ）なことをごまかしながら",
    "誰（だれ）もが目（め）をつぶり",
    "一人（ひとり）ぼっちになりそうになっても",
    "もう大丈夫（だいじょうぶ）だから",
    "-----------------------------",
    "いつか又（また）大（おお）きな波（なみ）が",
    "あなたを連（つ）れ去（さ）ろうとしても",
    "全（すべ）ての力（ちから）使（つか）い果（は）たし",
    "守（まも）ってあげるから",
    "時間（じかん）は過（す）ぎ 人（ひと）は流（なが）れ",
    "何（なに）もかも見（み）えなくなっても",
    "ここに居（い）るすぐ傍（そば）に",
    "それだけが僕（ぼく）の全（すべ）て",
    "-----------------------------",
    "不安（ふあん）を抱（いだ）き",
    "悲（かな）しみに打（う）たれ",
    "信（しん）じる事（こと）に挫（くじ）けそうになっても",
    "あなたを想（おも）い唄（うた）い続（つづ）けて行（い）く",
    "それだけが",
    "-----------------------------",
    "僕（ぼく）の全（すべ）て",
  ],
  romaji: [
    "sukoshi zutsu machi no kaze mo tsumetaku natsu te ki ta kara ",
    "kaze wo hiki yasui anata no koto ga ki ni nari masu",
    "fuyu no nioi ga boku wo toorinuke hajimeru to",
    "afureru hodo setsunaku te ai taku te",
    "-----------------------------",
    "kizutsuki nagara mogaki nagara",
    "bokutachi ha ashita toiu nichi wo yumemi te iki te iku",
    "-----------------------------",
    "itsuka mata dou shoumonaku sabishiku natsu ta sono toki ha ",
    "doko ni i te mo nani wo shi te te mo kaketsuke te ageru kara",
    "arifure teru kotoba nante sutesatsu te shimao u ",
    "nani mo ira nai anata ga iru sore dake ga boku no subete",
    "-----------------------------",
    "konnen ha yuki ga furu no ka na ? ",
    "bishonure ni natsu te hashai da ano nichi ",
    "oritsumotsu ta masshiro na yuki ha ",
    "subete no koto wo tsutsumikon de iku daro u",
    "-----------------------------",
    "tomadoi nagara tsuma zuki nagara",
    "bokutachi ha kinou toiu nichi wo kamishime te arui te iku",
    "-----------------------------",
    "itsuka mata dou shoumonaku sabishiku natsu ta sono toki ha ",
    "doko ni i te mo nani wo shi te te mo kaketsuke te ageru kara",
    "arifure te iru kotoba nante sutesatsu te shimao u ",
    "nani mo ira nai anata ga iru sore dake ga boku no subete",
    "-----------------------------",
    "Wo, ho - ho - ho -",
    "daiji na koto wo gomakashi nagara dare mo ga me wo tsuburi ",
    "hitoribotchi ni nari sou ni natsu te mo mou daijoubu da kara",
    "-----------------------------",
    "itsuka mata ookina nami ga anata wo tsuresaro u toshite mo",
    "subete no chikara tsukaihatashi mamotsu te ageru kara ",
    "jikan ha sugi nin ha nagare nani mo kamo mie naku natsu te mo",
    "koko ni iru sugu bou ni sore dake ga boku no subete",
    "-----------------------------",
    "fuan wo daki kanashimi ni uta re",
    "shinjiru koto ni kujike sou ni natsu te mo",
    "anata wo omoi utai tsuzuke te iku sore dake ga boku no subete",
  ],
};

export default itsuka;
