import type { LyricsSong } from "./types";

const song: LyricsSong = {
  title: "真夜中のドア (Stay With Me)",
  jp: [
    "To you",
    "Yes, my love, to you",
    "Yes, my love, to you, you",
    "To you",
    "-----------------------------",
    "私は私 貴方は貴方と",
    "昨夜言ってた そんな気もするわ",
    "グレイのジャケットに",
    "見覚えがある コーヒーのしみ (Oh)",
    "相変らずなのね",
    "ショーウィンドウに 二人映れば (Oh)",
    "-----------------------------",
    "Stay with me",
    "真夜中のドアをたたき",
    "帰らないでと泣いた (Oh)",
    "あの季節が 今 目の前",
    "Stay with me",
    "口ぐせを言いながら",
    "二人の瞬間を抱いて (Oh)",
    "まだ忘れず 大事にしていた",
    "-----------------------------",
    "恋と愛とは 違うものだよと",
    "昨夜言われた そんな気もするわ",
    "二度目の冬が来て",
    "離れていった貴方の心 (Oh)",
    "ふり返ればいつも",
    "そこに 貴方を感じていたの (Oh)",
    "-----------------------------",
    "Stay with me",
    "真夜中のドアをたたき",
    "心に穴があいた (Oh)",
    "あの季節が 今 目の前",
    "Stay with me",
    "淋しさまぎらわして",
    "置いたレコードの針 (Oh)",
    "同じメロディ 繰り返していた",
    "-----------------------------",
    "Stay with me",
    "真夜中のドアをたたき",
    "帰らないでと泣いた (Oh)",
    "あの季節が 今 目の前",
    "Stay with me",
    "口ぐせを言いながら",
    "二人の瞬間を抱いて (Oh)",
    "まだ忘れず 暖めてた",
    "Stay with me",
    "真夜中のドアをたたき",
    "帰らないでと泣いた (Oh)",
    "あの季節が 今 目の前",
    "Stay with me",
    "口ぐせを言いながら",
    "二人の瞬間を抱いて (Oh)",
    "まだ忘れず 暖めてた",
    "Stay with me",
    "真夜中のドアをたたき",
    "帰らないでと泣いた (Oh)",
    "あの季節が 今 目の前",
    "Stay with me",
  ],
  furigana: [
    "To you",
    "Yes, my love, to you",
    "Yes, my love, to you, you",
    "To you",
    "-----------------------------",
    "私（わたし）は私（わたし） 貴方（あなた）は貴方（あなた）と",
    "昨夜（ゆうべ）言（い）ってた そんな気（き）もするわ",
    "グレイのジャケットに",
    "見覚（みおぼ）えがある コーヒーのしみ (Oh)",
    "相変（あいか）らずなのね",
    "ショーウィンドウに 二人（ふたり）映（うつ）れば (Oh)",
    "-----------------------------",
    "Stay with me",
    "真夜中（まよなか）のドアをたたき",
    "帰（かえ）らないでと泣（な）いた (Oh)",
    "あの季節（きせつ）が 今（いま） 目（め）の前（まえ）",
    "Stay with me",
    "口（くち）ぐせを言（い）いながら",
    "二人（ふたり）の瞬間（しゅんかん）を抱（だ）いて (Oh)",
    "まだ忘（わす）れず 大事（だいじ）にしていた",
    "-----------------------------",
    "恋（こい）と愛（あい）とは 違（ちが）うものだよと",
    "昨夜（ゆうべ）言（い）われた そんな気（き）もするわ",
    "二度目（にどめ）の冬（ふゆ）が来（き）て",
    "離（はな）れていった貴方（あなた）の心（こころ） (Oh)",
    "ふり返（かえ）ればいつも",
    "そこに 貴方（あなた）を感（かん）じていたの (Oh)",
    "-----------------------------",
    "Stay with me",
    "真夜中（まよなか）のドアをたたき",
    "心（こころ）に穴（あな）があいた (Oh)",
    "あの季節（きせつ）が 今（いま） 目（め）の前（まえ）",
    "Stay with me",
    "淋（さび）しさまぎらわして",
    "置（お）いたレコードの針（はり） (Oh)",
    "同（おな）じメロディ 繰（く）り返（かえ）していた",
    "-----------------------------",
    "Stay with me",
    "真夜中（まよなか）のドアをたたき",
    "帰（かえ）らないでと泣（な）いた (Oh)",
    "あの季節（きせつ）が 今（いま） 目（め）の前（まえ）",
    "Stay with me",
    "口（くち）ぐせを言（い）いながら",
    "二人（ふたり）の瞬間（しゅんかん）を抱（だ）いて (Oh)",
    "まだ忘（わす）れず 暖（あたた）めてた",
    "Stay with me",
    "真夜中（まよなか）のドアをたたき",
    "帰（かえ）らないでと泣（な）いた (Oh)",
    "あの季節（きせつ）が 今（いま） 目（め）の前（まえ）",
    "Stay with me",
    "口（くち）ぐせを言（い）いながら",
    "二人（ふたり）の瞬間（しゅんかん）を抱（だ）いて (Oh)",
    "まだ忘（わす）れず 暖（あたた）めてた",
    "Stay with me",
    "真夜中（まよなか）のドアをたたき",
    "帰（かえ）らないでと泣（な）いた (Oh)",
    "あの季節（きせつ）が 今（いま） 目（め）の前（まえ）",
    "Stay with me",
  ],
  romaji: [
    "To you",
    "Yes, my love, to you",
    "Yes, my love, to you, you",
    "To you",
    "-----------------------------",
    "Watashi wa watashi, anata wa anata to",
    "Yuube itteta son'na ki mo suru wa",
    "Gurei no jaketto ni",
    "Mioboe ga aru koohii no shimi (Ooh)",
    "Aikawarazu na no ne",
    "Shoo windou ni futari utsureba (Ooh)",
    "-----------------------------",
    "Stay with me",
    "Mayonaka no doa o tataki",
    "Kaeranaide to naita (Ooh)",
    "Ano kisetsu ga ima me no mae",
    "Stay with me",
    "Kuchiguse wo ii nagara",
    "Futari no toki wo daite (Ooh)",
    "Mada wasurezu",
    "Daiji ni shite ita",
    "-----------------------------",
    "Koi to ai to wa chigau mono dayo to",
    "Yuube iwareta son'na ki mo suru wa",
    "Nidome no fuyu ga kite",
    "Hanarete itta anata no kokoro (Ooh)",
    "Furi kaereba itsumo",
    "Soko ni anata wo kanjite ita no (Ooh)",
    "-----------------------------",
    "Stay with me",
    "Mayonaka no doa o tataki",
    "Kokoro ni ana ga aita (Ooh)",
    "Ano kisetsu ga ima me no mae",
    "Stay with me",
    "Samishisa magirawashite",
    "Oita rekoodo no hari (Ooh)",
    "Onaji merodi kurikaeshite ita",
    "-----------------------------",
    "Stay with me",
    "Mayonaka no doa o tataki",
    "Kaeranaide to naita (Ooh)",
    "Ano kisetsu ga ima me no mae",
    "Stay with me",
    "Kuchiguse wo ii nagara",
    "Futari no toki wo daite (Ooh)",
    "Mada wasurezu atatameteta",
    "Stay with me",
    "Mayonaka no doa o tataki",
    "Kaeranaide to naita (Ooh)",
    "Ano kisetsu ga ima me no mae",
    "Stay with me",
    "Kuchiguse wo ii nagara",
    "Futari no toki wo daite (Ooh)",
    "Mada wasurezu atatameteta",
    "Stay with me",
    "Mayonaka no doa o tataki",
    "Kaeranaide to naita (Ooh)",
    "Ano kisetsu ga ima me no mae",
    "Stay with me",
  ],
};

export default song;
