import { ElementType } from "../../ElementType";
import { monsters, type Monster } from "../../monsters";

export const monstersExtendedUniverse: Monster[] = [
  {
    id: 'southCarolina-0001',
    name: 'Dripkin',
    trainerId: 'south-caro-4b1a-4321-000000000001',
    hp: 50,
    attack: 30,
    defense: 30,
    specialAttack: 70,
    specialDefense: 40,
    speed: 80,
    type: ElementType.Water,
    secondType: null,
    image: '/images/monsters/extendedUniverse/southCarolina/pkmnsquadSc1a.png',
    description: 'Dripkin is a playfull pokemon who loves to play with water',
    inspiration: 'Water Droplet', // Added inspiration
    attack1: {
      name: 'Plop',
      type: ElementType.Water,
      isPhysical: false,
      damage: 25,
      powerPoints: 10,
      accuracy: 1,
    },
    attack2: {
      name: 'Mental Wave',
      type: ElementType.Psychic,
      isPhysical: false,
      damage: 40,
      powerPoints: 4,
      accuracy: 0.75,
    },
  },
  {
    id: 'southCarolina-0002',
    name: 'Aquastride',
    trainerId: 'south-caro-4b1a-4321-000000000001',
    hp: 65,
    attack: 60,
    defense: 55,
    specialAttack: 95,
    specialDefense: 65,
    speed: 100,
    type: ElementType.Water,
    secondType: ElementType.Psychic,
    image: '/images/monsters/extendedUniverse/southCarolina/pkmnsquadSc1b.png',
    description: 'Aquastride still has a playfull nature like Dripkin but learns its psychic power and gets more serious',
    inspiration: 'baby water horse', // Added inspiration
    attack1: {
      name: 'Plop',
      type: ElementType.Water,
      isPhysical: false,
      damage: 25,
      powerPoints: 10,
      accuracy: 1,
    },
    attack2: {
      name: 'Mental Wave',
      type: ElementType.Psychic,
      isPhysical: false,
      damage: 40,
      powerPoints: 4,
      accuracy: 0.75,
    },
  },
  {
    id: 'southCarolina-0003',
    name: 'Splishingo',
    trainerId: 'south-caro-4b1a-4321-000000000001',
    hp: 90,
    attack: 85,
    defense: 65,
    specialAttack:125,
    specialDefense:75,
    speed:120,
    type: ElementType.Water,
    secondType: ElementType.Psychic,
    image: '/images/monsters/extendedUniverse/southCarolina/pkmnsquadSc1c.png',
    description: 'It is said Splishingo can use its infinite water source on its mane to launch at enemies with its psychic mind.',
    inspiration: 'Water horse', // Added inspiration
    attack1: {
      name: 'Hydrolyzing Mind',
      type: ElementType.Water,
      isPhysical: false,
      damage: 60,
      powerPoints: 2,
      accuracy: 0.5,
    },
    attack2: {
      name: 'Mental Wave',
      type: ElementType.Psychic,
      isPhysical: false,
      damage: 40,
      powerPoints: 4,
      accuracy: 0.75,
    },
  },
  {
    id: 'southCarolina-0004',
    name: 'Pixtix',
    trainerId: 'south-caro-4b1a-4321-000000000002',
    hp: 50,
    attack: 35,
    defense: 45,
    specialAttack: 48,
    specialDefense: 64,
    speed: 58,
    type: ElementType.Fairy,
    secondType: null,
    image: '/images/monsters/extendedUniverse/southCarolina/pkmnsquadSc2a.png',
    description: 'This pokemon is found on cold mountains. Many trainers think they were left behind but really go there to train.',
    inspiration: 'Pixie', // Added inspiration
    attack1: {
      name: 'Pixie Punch',
      type: ElementType.Fairy,
      isPhysical: true,
      damage: 40,
      powerPoints: 4,
      accuracy: 0.75,
    },
    attack2: {
      name: 'Fairy Wind',
      type: ElementType.Fairy,
      isPhysical: false,
      damage: 25,
      powerPoints: 10,
      accuracy: 1,
    },
  },
  {
    id: 'southCarolina-0005',
    name: 'Frostix',
    trainerId: 'south-caro-4b1a-4321-000000000002',
    hp: 70,
    attack: 65,
    defense: 60,
    specialAttack: 55,
    specialDefense: 82,
    speed: 78,
    type: ElementType.Fairy,
    secondType: ElementType.Ice,
    image: '/images/monsters/extendedUniverse/southCarolina/pkmnsquadSc2b.png',
    description: 'After training in the mountains this pokemon has adapted to its environment.',
    inspiration: 'Pixie', // Added inspiration
    attack1: {
      name: 'Ice Spinner',
      type: ElementType.Ice,
      isPhysical: true,
      damage: 60,
      powerPoints: 2,
      accuracy: 0.5,
    },
    attack2: {
      name: 'Moon Blast',
      type: ElementType.Fairy,
      isPhysical: false,
      damage: 40,
      powerPoints: 4,
      accuracy: 0.75,
    },
  },
  {
    id: 'southCarolina-0006',
    name: 'Queenstix',
    trainerId: 'south-caro-4b1a-4321-000000000002',
    hp: 85,
    attack: 89,
    defense: 87,
    specialAttack: 80,
    specialDefense: 105,
    speed: 94,
    type: ElementType.Fairy,
    secondType: ElementType.Ice,
    image: '/images/monsters/extendedUniverse/southCarolina/pkmnsquadSc2c.png',
    description: 'Queenstix have conquered the moutain they are on. They protect the moutain with might.',
    inspiration: 'Pixie', // Added inspiration
    attack1: {
      name: 'Glacial Spear',
      type: ElementType.Ice,
      isPhysical: true,
      damage: 60,
      powerPoints: 2,
      accuracy: 0.5,
    },
    attack2: {
      name: 'Ice Beam',
      type: ElementType.Ice,
      isPhysical: false,
      damage: 40,
      powerPoints: 4,
      accuracy: 0.75,
    },
  },
];

export const getExtendedUniverseMonsters = () => {
  return [...monstersExtendedUniverse, ...monsters];
}