import type { LyricsSong } from "./types";

const song: LyricsSong = {
  title: "Land",
  jp: [
    "おはようここのところなんか体がだるくて仕方がないよ",
    "積もり積もった疲労のせいか？破裂しそうなハートのせいか？",
    "発狂寸前のニュースが TVから流れまくっていても",
    "今ひとつ手触りがないよ実感に事欠けているんだ",
    "-----------------------------",
    "迫り来る世界の終わりなんかより",
    "明日の我が身を案じてんだ 日々の暮らしに必死なんですよ ",
    "現実問題",
    "-----------------------------",
    "一体どんな未来をこの先描けという",
    "そして何を残して行けばいいの？",
    "行き詰まりうつむく この両足が踏みしめてんのは",
    "紛れもない 僕らのLAND",
    "-----------------------------",
    "こんにちはご機嫌はいかが？悪くもないし良くもないかな",
    "時々チューニングが合わずに 上手く笑えず引きつりそうです",
    "顔も名前も知らない同士 あげ足とったり慰め合ったり",
    "そしてみんなは繋がっている あまり馴染めず嫌気がさした",
    "-----------------------------",
    "この指止まれ孤独を持ち寄って",
    "結果誰かを愛したいんだ そして誰かに愛されたいのだ 一期一会",
    "-----------------------------",
    "一回こっきりの人生 出会いや別れや",
    "つまり誰を大切に生きていくの？",
    "守るべき人さえ守らずに何処へ行くというのだろう",
    "それじゃあんまりだ 無力な縁",
    "-----------------------------",
    "very merry-go-land very merry-go-land",
    "-----------------------------",
    "やけになんな病んでく 明日でも",
    "そんでもかと こんでもかともがく 僕らは",
    "-----------------------------",
    "おやすみなさい眠る家族は大気汚染に法えて暮らす",
    "誰かを攻めるつもりはないが本当にもう時間がないんだ",
    "目に見えること見えないことも 同じくらい重要だから",
    "天は我らに何を問うのか 五感をフルに感じてみんだ",
    "-----------------------------",
    "忘れちゃならない悲しい物語",
    "胸に抱えた痛みだって プラスに変えて行ける",
    "ように願う 出発進行",
    "-----------------------------",
    "一世一代の転機 もしかしたら今かも 嘆くより自分が始めりゃいい",
    "ぬかるんだ道だって何度でも強く歩き出してやる",
    "勝手に決めんな 全てのEND",
    "愛するここが 紛れもない 僕らのLAND",
    "LAND LAND LAND",
  ],
  furigana: [
    "おはようここのところなんか体（からだ）がだるくて仕方（しかた）がないよ",
    "積（つ）もり積（つ）もった疲労（ひ）のせいか？破裂（はれつ）しそうなハートのせいか？",
    "発狂寸前（はすんぜん）のニュー（ん）スが TVから流（なが）れまくっていても",
    "今（いま）ひとつ手触（てざわ）りがないよ実感（じっかん）に事欠（ことか）けているんだ",
    "-----------------------------",
    "迫（せま）り来（く）る世界（せかい）の終（お）わりなんかより",
    "明日（あす）の我（わ）が身（み）を（お）案（あん）じてんだ 日々（ひび）の暮（く）らしに必死（ひっし）なんですよ",
    "現実問題（げんじつもんだい）",
    "-----------------------------",
    "一体（いったい）どんな未来を（みらいお）この先（さき）描（えが）けという",
    "そして何（なに）を（お）残（のこ）して行（ゆ）けばいいの？",
    "行（ゆ）き詰（ず）まりうつむく この両足（あし）が踏（ふ）みしめてんのは",
    "紛（まぎ）れもない 僕（ぼく）らのLAND",
    "-----------------------------",
    "こんにちはご機嫌（きげん）はいかが？悪（わる）くもないし良（よ）くもないかな",
    "時々チュー（ときどき）ニングが合（あ）わずに 上手（うま）く笑（わら）えず引（ひ）きつりそうです",
    "顔（かお）も名前（なまえ）も知（し）らない同士 （し）あげ足（あし）とったり慰（なぐさ）め合（あ）ったり",
    "そしてみんなは繋（つな）がっている あまり馴染（なじ）めず嫌気（いやけ）がさした",
    "-----------------------------",
    "この指（ゆび）止（と）まれ孤独を持（こどくおも）ち寄（よ）って",
    "結果誰（けっ）かを愛（だれかおあい）したいんだ そして誰（だれ）かに愛（あい）されたいのだ 一期一会（いちごいちえ）",
    "-----------------------------",
    "一回（いっかい）こっきりの人生 出会（じんであ）いや別（わか）れや",
    "つまり誰を大切（だれおたいせつ）に生（い）きていくの？",
    "守（まも）るべき人（ひと）さえ守（まも）らずに何処へ行（どこえい）くというのだろう",
    "それじゃあんまりだ 無力（むりょく）な縁（えん）",
    "-----------------------------",
    "very merry-go-land very merry-go-land",
    "-----------------------------",
    "やけになんな病（や）んでく 明日（あした）でも",
    "そんでもかと こんでもかともがく 僕（ぼく）らは",
    "-----------------------------",
    "おやすみなさい眠（ねむ）る家族（かぞく）は大気汚染（たいきおせん）に法（おび）えて暮（く）らす",
    "誰（だれ）かを（お）攻（せ）めるつもりはないが本当（ほん）にもう時間（じかん）がないんだ",
    "目（め）に見（み）えること見（み）えないことも 同（おな）じくらい重要だから",
    "天（てん）は我（われ）らに何（なに）を（お）問（と）うのか 五感を（ごかんお）フルに感（かん）じてみんだ",
    "-----------------------------",
    "忘（わす）れちゃならない悲（かな）しい物語（ものがたり）",
    "胸（むね）に抱（かか）えた痛（いた）みだって プラスに変（か）えて行（い）ける",
    "ように願（ねが）う 出発進行（しゅっぱつしん）",
    "-----------------------------",
    "一世一代（いいちだい）の転機 （てんき）もしかしたら今（いま）かも 嘆（なげ）くより自分（じぶん）が始（はじ）めりゃいい",
    "ぬかるんだ道（みち）だって何度（なんど）でも強（つよ）く歩（ある）き出（だ）してやる",
    "勝手（かって）に決（き）めんな 全（すべ）てのEND",
    "愛（あい）するここが 紛（まぎ）れもない 僕（ぼく）らのLAND",
    "LAND LAND LAND",
  ],
  romaji: [
    "Ohayō. Koko no tokoro nanka, karada ga darukute shikata ga nai yo.",
    "Tsumori tsumotta hirō no sei ka? Haretsu shisō na hāto no sei ka?",
    "Hakkyō sunzen no nyūsu ga TV kara nagare makutte ite mo,",
    "Imahitotsu tezawari ga nai yo. Jikkan ni kotokakete iru n da.",
    "-----------------------------",
    "Semarikuru sekai no owari nanka yori,",
    "Asu no wagami o anjite n da. Hibi no kurashi ni hisshi na n desu yo. ",
    "Genjitsu mondai.",
    "-----------------------------",
    "Ittai donna mirai o kono saki egake to iu?",
    "Soshite nani o nokoshite yukeba ii no?",
    "Yukizumari utsumuku kono ryōashi ga fumishimete n no wa,",
    "Magire mo nai bokura no LAND.",
    "-----------------------------",
    "Konnichiha. Gokigen wa ikaga? Waruku mo nai shi, yoku mo nai ka na.",
    "Tokidoki chūningu ga awazu ni, umaku waraezu, hikitsurisō desu.",
    "Kao mo namae mo shiranai dōshi ageashi tottari nagusameattari,",
    "Soshite minna wa tsunagatte iru. Amari najimezu iyake ga sashita.",
    "-----------------------------",
    "Kono yubi tomare. Kodoku o mochiyotte,",
    "Kekka dareka o aishitai n da. Soshite dareka ni aisaretai no da. Ichigoichie.",
    "-----------------------------",
    "Ikkaikokkiri no jinsē, deai ya wakare ya,",
    "Tsumari dare o taisetsu ni ikite iku no?",
    "Mamorubeki hito sae mamorazu ni doko e iku to iu no darō",
    "Sore ja anmari da. Muryoku na en.",
    "-----------------------------",
    "very merry-go-land very merry-go-land",
    "-----------------------------",
    "Yake ni nan na, yande ku ashita demo.",
    "Son demo ka to, kon demo ka to mogaku, bokura wa.",
    "-----------------------------",
    "Oyasumi nasai. Nemuru kazoku wa, taiki osen ni obiete kurasu.",
    "Dareka o semeru tsumori wa nai ga, hontō ni mō jikan ga nai n da.",
    "Me ni mieru koto. mienai koto mo, onaji kurai jūyō da kara,",
    "Ten wa warera ni nani o tou no ka, gokan o furu ni kanjite min da.",
    "-----------------------------",
    "Wasurecha naranai kanashii monogatari,",
    "Mune ni kakaeta itami datte, purasu ni kaete ikeru ",
    "yōni negau. Shuppatsu shinkō.",
    "-----------------------------",
    "Issēichidai no tenki. Moshika shitara ima kamo. Nageku yori jibun ga hajimerya ii.",
    "Nukarunda michi datte, nando demo tsuyoku arukidashite yaru.",
    "Katte ni kimen na, subete no END.",
    "Aisuru koko ga magire mo nai bokura no LAND.",
    "LAND LAND LAND",
    "-----------------------------",
  ],
};

export default song;
