import type { LyricsSong } from "./types";

const senNoYoruWoKoete: LyricsSong = {
  title: "千の夜をこえて (Sen no Yoru wo Koete)",
  jp: [
    "愛されたい　でも愛そうとしない",
    "その繰り返しのなかを彷徨って",
    "僕が見つけた答えは",
    "一つ怖くたって傷ついたって",
    "好きな人には好きって　伝えるんだ",
    "-----------------------------",
    "あなたが僕を愛しているか",
    "愛してないか」なんてことは",
    "もうどっちでもいいんだ",
    "どんな願い望もうが",
    "この世界にはかえられぬものが",
    "沢山あるだろう",
    "そう　そして僕があなたを",
    "愛してるという事実だけは",
    "だれにも変えられぬ　真実だから",
    "-----------------------------",
    "千の夜をこえて　あなたに伝えたい",
    "伝えなきならないことがある",
    "愛されたい　でも　愛そうとしない",
    "その繰り返しのなかを彷徨って",
    "僕が見つけた答えは",
    "一つ怖くたって傷ついたって",
    "好きな人には好きって　伝えるんだ",
    "気持ちを言葉にするのは怖いよ",
    "でも好きな人には好きって伝えるんだ",
    "-----------------------------",
    "この広い世界に巡りあう喜びを言葉",
    "じゃ言い表せないね",
    "だから僕たちは微笑み",
    "色鮮やかに過ぎる秋を　ドレミで歌って",
    "冬を背に　春の木漏れ日を待ち",
    "新しく生まれ変わる　誰かを",
    "守れるようにと",
    "-----------------------------",
    "来た道と行く先　振り返ればいつでも",
    "臆病な目をしていた僕",
    "向き合いたい　でも素直になれない",
    "まっすぐに相手を愛せない日々を",
    "繰り返しては　一人ぼっちをいやがって",
    "あの日の僕は無傷のまま",
    "で人を愛そうとしていた",
    "-----------------------------",
    "千の夜をこえて　今あなたに会いに行こう",
    "伝えなきゃならないことがある",
    "愛されたい　でも愛そうとしない",
    "その繰り返しの中を彷徨って",
    "僕が見つけた答えは",
    "一つ怖くたって傷ついたって",
    "好きな人には好きって　伝えるんだ",
    "その思いが適わなくたって",
    "好きな人に好きって伝える",
    "それは　この世界で一番　素敵なことさ",
  ],
  furigana: [
    "愛（あい）されたい　でも愛（あい）そうとしない",
    "その繰（く）り返（かえ）しのなかを彷徨（さまよ）って",
    "僕（ぼく）が見（み）つけた答（こた）えは",
    "一（ひと）つ怖（こわ）くたって傷（きず）ついたって",
    "好（す）きな人（ひと）には好（す）きって　伝（つた）えるんだ",
    "-----------------------------",
    "あなたが僕（ぼく）を愛（あい）しているか",
    "愛（あい）してないか」なんてことは",
    "もうどっちでもいいんだ",
    "どんな願（ねが）い望（のぞ）もうが",
    "この世界（せかい）にはかえられぬものが",
    "沢山（たくさん）あるだろう",
    "そう　そして僕（ぼく）があなたを",
    "愛（あい）してるという事実（じじつ）だけは",
    "だれにも変（か）えられぬ　真実（しんじつ）だから",
    "-----------------------------",
    "千（せん）の夜（よる）をこえて　あなたに伝（つた）えたい",
    "伝（つた）えなきならないことがある",
    "愛（あい）されたい　でも　愛（あい）そうとしない",
    "その繰（く）り返（かえ）しのなかを彷徨（さまよ）って",
    "僕（ぼく）が見（み）つけた答（こた）えは",
    "一（ひと）つ怖（こわ）くたって傷（きず）ついたって",
    "好（す）きな人（ひと）には好（す）きって　伝（つた）えるんだ",
    "気持（きも）ちを言葉（ことば）にするのは怖（こわ）いよ",
    "でも好（す）きな人（ひと）には好（す）きって伝（つた）えるんだ",
    "-----------------------------",
    "この広（ひろ）い世界（せかい）に巡（めぐ）りあう喜（よろこ）びを言葉（ことば）",
    "じゃ言（い）い表（あらわ）せないね",
    "だから僕（ぼく）たちは微笑（ほほえ）み",
    "色鮮（いろあざ）やかに過（す）ぎる秋（あき）を　ドレミで歌（うた）って",
    "冬（ふゆ）を背（せ）に　春（はる）の木漏（こも）れ日（び）を待（ま）ち",
    "新（あたら）しく生（う）まれ変（か）わる　誰（だれ）かを",
    "守（まも）れるようにと",
    "-----------------------------",
    "来（き）た道（みち）と行（ゆ）く先（さき）　振（ふ）り返（かえ）ればいつでも",
    "臆病（おくびょう）な目（め）をしていた僕（ぼく）",
    "向（む）き合（あ）いたい　でも素直（すなお）になれない",
    "まっすぐに相手（あいて）を愛（あい）せない日々（ひび）を",
    "繰（く）り返（かえ）しては　一人（ひとり）ぼっちをいやがって",
    "あの日（ひ）の僕（ぼく）は無傷（むきず）のまま",
    "で人（ひと）を愛（あい）そうとしていた",
    "-----------------------------",
    "千（せん）の夜（よる）をこえて　今（いま）あなたに会（あ）いに行（い）こう",
    "伝（つた）えなきゃならないことがある",
    "愛（あい）されたい　でも愛（あい）そうとしない",
    "その繰（く）り返（かえ）しの中（なか）を彷徨（さまよ）って",
    "僕（ぼく）が見（み）つけた答（こた）えは",
    "一（ひと）つ怖（こわ）くたって傷（きず）ついたって",
    "好（す）きな人（ひと）には好（す）きって　伝（つた）えるんだ",
    "その思（おも）いが適（かな）わなくたって",
    "好（す）きな人（ひと）に好（す）きって伝（つた）える",
    "それは　この世界（せかい）で一番（いちばん）　素敵（すてき）なことさ",
  ],
  romaji: [
    "Aisaretai demo aisou to shinai",
    "Sono kurikaeshi no naka wo samayatte",
    "Boku ga mitsuketa kotae wa",
    "hitotsu kowakutatte kizutsuitatte",
    "Suki na hito ni wa suki tte tsutaerunda",
    "-----------------------------",
    "Anata ga boku wo aishite iru ka",
    "aishite inai ka nante koto wa",
    "Mou docchi demo iin da",
    "Donna ni negai nozomou ga",
    "Kono sekai ni wa kaerarenu mono ga",
    "takusan aru darou",
    "Sou soshite boku ga anata wo",
    "aishiteru to iu jijitsu dake wa",
    "Dare ni mo kaerarenu shinjitsu dakara",
    "-----------------------------",
    "Sen no yoru wo koete anata ni tsutaetai",
    "Tsutaenakya naranai koto ga aru",
    "Aisaretai demo aisou to shinai",
    "Sono kurikaeshi no naka wo samayatte",
    "Boku ga mitsuketa kotae wa",
    "hitotsu kowakutatte kizutsuitatte",
    "Suki na hito ni wa suki tte tsutaerunda",
    "Kimochi wo kotoba ni suru no wa kowai yo demo",
    "Suki na hito ni wa suki tte tsutaerunda",
    "-----------------------------",
    "Kono hiroi sekai de meguri au yorokobi wo kotoba",
    "jya ii arawasenai ne",
    "Dakara bokutachi wa hohoemi",
    "Iro azayaka ni sugiru aki wo doremi de utatte",
    "Fuyu wo se ni haru no komorebi wo machi",
    "Atarashiku umare kawaru dareka wo",
    "mamoreru youni to",
    "-----------------------------",
    "Kita michi to yukisaki furikaereba itsudemo",
    "okubyou na me wo shite ita boku",
    "Mukiaitai demo sunao ni narenai",
    "Massugu ni aite wo aisenai hibi wo",
    "Kurikaeshite wa hitoribocchi wo iyagatte",
    "Ano hi no boku wa mukizu na mama",
    "de hito wo aisou to shite ita",
    "-----------------------------",
    "Sen no yoru wo koete ima anata ni ai ni yukou",
    "Tsutaenakya naranai koto ga aru",
    "Aisaretai demo aisou to shinai",
    "Sono kurikaeshi no naka wo samayatte",
    "Boku ga mitsuketa kotae wa",
    "hitotsu kowakutatte kizutsuitatte",
    "Suki na hito ni wa suki tte tsutaerunda",
    "Sono omoi ga kanawanakutatte",
    "suki na hito ni suki tte tsutaeru",
    "Sore wa kono sekai de ichiban suteki na koto sa",
  ],
};

export default senNoYoruWoKoete;
