import type { LyricsSong } from "./types";

const tegami: LyricsSong = {
  title: "手紙 (Tegami)",
  jp: [
    "拝啓 この手紙読んでいるあなたは",
    "どこで何をしているのだろう",
    "-----------------------------",
    "15の僕には誰にも話せない",
    "悩みの種があるのです",
    "-----------------------------",
    "未来の自分に宛てて書く手紙なら",
    "きっと素直に打ち明けられるだろう",
    "-----------------------------",
    "今負けそうで泣きそうで",
    "消えてしまいそうな僕は",
    "誰の言葉を",
    "信じ歩けばいいの",
    "ひとつしかないこの胸が何度もバラバラに割れて",
    "苦しい中で今を生きている",
    "今を生きている",
    "-----------------------------",
    "拝啓 ありがとう15のあなたに",
    "伝えたいことがあるのです",
    "自分とは何でどこへ向かうべきか",
    "問い続ければ見えてくる",
    "-----------------------------",
    "荒れた青春の海は厳しいけれど",
    "明日の岸辺へと夢の船よ進め",
    "-----------------------------",
    "今負けないで泣かないで",
    "消えてしまいそうな時は",
    "自分の声を信じあるけばいいの",
    "大人の僕も傷ついて",
    "眠れない夜はあるけど",
    "苦くて甘い今生きている",
    "-----------------------------",
    "人生のすべてに意味があるから",
    "おお恐れずにあなたの夢を育てて",
    "La la la, la la la",
    "Keep on believing",
    "La la la, la la la",
    "Keep on believing, keep on believing, keep on believing",
    "-----------------------------",
    "負けそうで泣きそうで",
    "消えてしまいそうな僕は",
    "誰の言葉を信じあるけばいいの",
    "ああ 負けないで泣かないで",
    "消えてしまいそうな時は",
    "自分の声を信じあるけばいいの",
    "いつの時代も悲しみも",
    "避けては取れないけれど",
    "笑顔を見せて今を生きてゆこう",
    "今を生きてゆこう",
    "-----------------------------",
    "拝啓 この手紙読んでいるあなたが",
    "幸せなことを願います",
  ],
  furigana: [
    "拝啓（はいけい） この手紙（てがみ）読（よ）んでいるあなたは",
    "どこで何（なに）をしているのだろう",
    "-----------------------------",
    "15の僕（ぼく）には誰（だれ）にも話（はな）せない",
    "悩（なや）みの種（たね）があるのです",
    "-----------------------------",
    "未来（みらい）の自分（じぶん）に宛（あ）てて書（か）く手紙（てがみ）なら",
    "きっと素直（すなお）に打（う）ち明（あ）けられるだろう",
    "-----------------------------",
    "今（いま）負（ま）けそうで泣（な）きそうで",
    "消（き）えてしまいそうな僕（ぼく）は",
    "誰（だれ）の言葉（ことば）を",
    "信（しん）じ歩（ある）けばいいの",
    "ひとつしかないこの胸（むね）が何度（なんど）もバラバラに割（わ）れて",
    "苦（くる）しい中（なか）で今（いま）を生（い）きている",
    "今（いま）を生（い）きている",
    "-----------------------------",
    "拝啓（はいけい） ありがとう15のあなたに",
    "伝（つた）えたいことがあるのです",
    "自分（じぶん）とは何（なに）でどこへ向（む）かうべきか",
    "問（と）い続（つづ）ければ見（み）えてくる",
    "-----------------------------",
    "荒（あ）れた青春（せいしゅん）の海（うみ）は厳（きび）しいけれど",
    "明日（あした）の岸辺（きしべ）へと夢（ゆめ）の船（ふね）よ進（すす）め",
    "-----------------------------",
    "今（いま）負（ま）けないで泣（な）かないで",
    "消（き）えてしまいそうな時（とき）は",
    "自分（じぶん）の声（こえ）を信（しん）じあるけばいいの",
    "大人（おとな）の僕（ぼく）も傷（きず）ついて",
    "眠（ねむ）れない夜（よる）はあるけど",
    "苦（にが）くて甘（あま）い今（いま）生（い）きている",
    "-----------------------------",
    "人生（じんせい）のすべてに意味（いみ）があるから",
    "おお恐（おそ）れずにあなたの夢（ゆめ）を育（そだ）てて",
    "La la la, la la la",
    "Keep on believing",
    "La la la, la la la",
    "Keep on believing, keep on believing, keep on believing",
    "-----------------------------",
    "負（ま）けそうで泣（な）きそうで",
    "消（き）えてしまいそうな僕（ぼく）は",
    "誰（だれ）の言葉（ことば）を信（しん）じあるけばいいの",
    "ああ 負（ま）けないで泣（な）かないで",
    "消（き）えてしまいそうな時（とき）は",
    "自分（じぶん）の声（こえ）を信（しん）じあるけばいいの",
    "いつの時代（じだい）も悲（かな）しみも",
    "避（さ）けては取（と）れないけれど",
    "笑顔（えがお）を見（み）せて今（いま）を生（い）きてゆこう",
    "今（いま）を生（い）きてゆこう",
    "-----------------------------",
    "拝啓（はいけい） この手紙（てがみ）読（よ）んでいるあなたが",
    "幸（しあわ）せなことを願（ねが）います",
  ],
  romaji: [
    "Haikei, kono tegami yonde iru anata wa",
    "Doko de nani wo shite iru no darō",
    "-----------------------------",
    "15 no boku ni wa dare ni mo hanasenai",
    "Nayami no tane ga aru no desu",
    "-----------------------------",
    "Mirai no jibun ni atete kaku tegami nara",
    "Kitto sunao ni uchiakerareru darō",
    "-----------------------------",
    "Ima makesō de nakisō de",
    "Kiete shimai sō na boku wa",
    "Dare no kotoba wo",
    "Shinji arukeba ii no",
    "Hitotsu shika nai kono mune ga nando mo barabara ni warete",
    "Kurushii naka de ima wo ikite iru",
    "Ima wo ikite iru",
    "-----------------------------",
    "Haikei, arigatō 15 no anata ni",
    "Tsutaetai koto ga aru no desu",
    "Jibun to wa nani de doko e mukau beki ka",
    "Toi tsudzukereba miete kuru",
    "-----------------------------",
    "Areta seishun no umi wa kibishii keredo",
    "Ashita no kishibe e to yume no fune yo susume",
    "-----------------------------",
    "Ima makenaide nakanai de",
    "Kiete shimai sō na toki wa",
    "Jibun no koe wo shinji arukeba ii no",
    "Otona no boku mo kizutsuite",
    "Nemurenai yoru wa aru kedo",
    "Nigakute amai ima ikite iru",
    "-----------------------------",
    "Jinsei no subete ni imi ga aru kara",
    "Ōosorezu ni anata no yume wo sodatete",
    "La la la, la la la",
    "Keep on believing",
    "La la la, la la la",
    "Keep on believing, keep on believing, keep on believing",
    "-----------------------------",
    "Makesō de nakisō de",
    "Kiete shimai sō na boku wa",
    "Dare no kotoba wo shinji arukeba ii no",
    "Ā makenaide nakanaide",
    "Kiete shimai sō na toki wa",
    "Jibun no koe wo shinji arukeba ii no",
    "Itsu no jidai mo kanashimi mo",
    "Sakete wa torenai keredo",
    "Egao wo misete ima wo ikite yukō",
    "Ima wo ikite yukō",
    "-----------------------------",
    "Haikei, kono tegami yonde iru anata ga",
    "Shiawase na koto wo negaimasu",
  ],
};

export default tegami;
