import type { LyricsSong } from "./types";

const tegami: LyricsSong = {
  title: "栄光の架橋 (Eikou No Kakehashi)",
  jp: [
    "誰にも見せない",
    "泪があった",
    "人知れず流した",
    "泪があった。",
    "けして平らな",
    "道ではなかった",
    "けれど確かに",
    "歩んで来た道だ。",
    "-----------------------------",
    "あの時想い",
    "描いた",
    "夢の途中に。",
    "今も",
    "何度も何度も",
    "あきらめかけた",
    "夢の途中",
    "-----------------------------",
    "いくつもの",
    "日々を越えて",
    "辿り着いた",
    "今がある",
    "だからもう",
    "迷わずに",
    "進めばいい",
    "栄光の",
    "架橋へと",
    "-----------------------------",
    "悔しくて",
    "眠れなかった",
    "夜があった",
    "恐くて",
    "震えていた",
    "夜があった",
    "-----------------------------",
    "もう駄目だと",
    "全てが",
    "嫌になって",
    "逃げ出そうと",
    "した時も",
    "想い出せば",
    "こうして",
    "たくさんの",
    "支えの中で",
    "歩いて来た",
    "-----------------------------",
    "悲しみや",
    "苦しみの先に",
    "それぞれの",
    "光がある",
    "さあ行こう",
    "振り返らず",
    "走り出せばいい",
    "希望に満ちた",
    "空へ",
    "-----------------------------",
    "誰にも見せない",
    "泪があった",
    "人知れず流した",
    "泪があった",
    "-----------------------------",
    "いくつもの",
    "日々を越えて",
    "辿り着いた",
    "今がある",
    "だからもう",
    "迷わずに",
    "進めばいい",
    "栄光の",
    "架橋へと",
    "-----------------------------",
    "終わらない",
    "その旅へと",
    "-----------------------------",
    "君の心へ続く",
    "架橋へと",
  ],
  romaji: [
    "dare nimo misenai",
    "namida ga atta",
    "hito-shirezu nagashita",
    "namida ga atta",
    "kesite tairana",
    "michi dewa nakatta",
    "keredo tashikani",
    "ayunde kita michida",
    "-----------------------------",
    "anotoki omoi",
    "ega ita",
    "yume no tochyu ni",
    "ima mo",
    "nando mo nando mo",
    "akirame kaketa",
    "yume no tochuu",
    "-----------------------------",
    "ikutsu mono",
    "hibi wo koete",
    "tadori tsuita",
    "ima ga aru",
    "dakara moo",
    "mayowazu ni",
    "susume ba ii",
    "eikoo no",
    "kakehashi eto",
    "-----------------------------",
    "kyashiku te",
    "nemurena katta",
    "yoru ga atta",
    "kowaku te",
    "furuete ita",
    "yoru ga atta",
    "-----------------------------",
    "moo damedato",
    "subete ga",
    "iya ni natte",
    "nige dasooto",
    "shita tokimo",
    "omoi daseba",
    "koo-shite",
    "takusan no",
    "sasaeno nakade",
    "aruite kita",
    "-----------------------------",
    "kana-shimi ya",
    "kuru-shimi no sakini",
    "sorezore no",
    "hikari ga aru",
    "saa yukoo",
    "furikae razu",
    "hashiri daseba ii",
    "kiboo ni michita",
    "sora e",
    "-----------------------------",
    "dare nimo misenai",
    "namida ga atta",
    "hito shirezu nagashita",
    "namida ga atta",
    "-----------------------------",
    "ikutsu mono",
    "hibi wo koete",
    "tadori tsuita",
    "ima ga aru",
    "dakara moo",
    "mayowazu ni",
    "susume ba ii",
    "eikoo no",
    "kake-hashi eto",
    "-----------------------------",
    "owara nai",
    "sono tabi eto",
    "-----------------------------",
    "kimi no kokoro e tsuzuku",
    "kake-hashi eto",
  ],
};

export default tegami;
