export const jp = [
    "拝啓 この手紙読んでいるあなたは",
    "どこで何をしているのだろう",
    "-----------------------------",
    "15の僕には誰にも話せない",
    "悩みの種があるのです",
    "-----------------------------",
    "未来の自分に宛てて書く手紙なら",
    "きっと素直に打ち明けられるだろう",
    "-----------------------------",
    "今負けそうで泣きそうで",
    "消えてしまいそうな僕は",
    "誰の言葉を",
    "信じ歩けばいいの",
    "ひとつしかないこの胸が何度もバラバラに割れて",
    "苦しい中で今を生きている",
    "今を生きている",
    "-----------------------------",
    "拝啓 ありがとう15のあなたに",
    "伝えたいことがあるのです",
    "自分とは何でどこへ向かうべきか",
    "問い続ければ見えてくる",
    "-----------------------------",
    "荒れた青春の海は厳しいけれど",
    "明日の岸辺へと夢の船よ進め",
    "-----------------------------",
    "今負けないで泣かないで",
    "消えてしまいそうな時は",
    "自分の声を信じあるけばいいの",
    "大人の僕も傷ついて",
    "眠れない夜はあるけど",
    "苦くて甘い今生きている",
    "-----------------------------",
    "人生のすべてに意味があるから",
    "おお恐れずにあなたの夢を育てて",
    "La la la, la la la",
    "Keep on believing",
    "La la la, la la la",
    "Keep on believing, keep on believing, keep on believing",
    "-----------------------------",
    "負けそうで泣きそうで",
    "消えてしまいそうな僕は",
    "誰の言葉を信じあるけばいいの",
    "ああ 負けないで泣かないで",
    "消えてしまいそうな時は",
    "自分の声を信じあるけばいいの",
    "いつの時代も悲しみも",
    "避けては取れないけれど",
    "笑顔を見せて今を生きてゆこう",
    "今を生きてゆこう",
    "-----------------------------",
    "拝啓 この手紙読んでいるあなたが",
    "幸せなことを願います",
]

export const romaji = [
    "Haikei, kono tegami yonde iru anata wa",
    "Doko de nani wo shite iru no darō",
    "-----------------------------",
    "15 no boku ni wa dare ni mo hanasenai",
    "Nayami no tane ga aru no desu",
    "-----------------------------",
    "Mirai no jibun ni atete kaku tegami nara",
    "Kitto sunao ni uchiakerareru darō",
    "-----------------------------",
    "Ima makesō de nakisō de",
    "Kiete shimai sō na boku wa",
    "Dare no kotoba wo",
    "Shinji arukeba ii no",
    "Hitotsu shika nai kono mune ga nando mo barabara ni warete",
    "Kurushii naka de ima wo ikite iru",
    "Ima wo ikite iru",
    "-----------------------------",
    "Haikei, arigatō 15 no anata ni",
    "Tsutaetai koto ga aru no desu",
    "Jibun to wa nani de doko e mukau beki ka",
    "Toi tsudzukereba miete kuru",
    "-----------------------------",
    "Areta seishun no umi wa kibishii keredo",
    "Ashita no kishibe e to yume no fune yo susume",
    "-----------------------------",
    "Ima makenaide nakanai de",
    "Kiete shimai sō na toki wa",
    "Jibun no koe wo shinji arukeba ii no",
    "Otona no boku mo kizutsuite",
    "Nemurenai yoru wa aru kedo",
    "Nigakute amai ima ikite iru",
    "-----------------------------",
    "Jinsei no subete ni imi ga aru kara",
    "Ōosorezu ni anata no yume wo sodatete",
    "La la la, la la la",
    "Keep on believing",
    "La la la, la la la",
    "Keep on believing, keep on believing, keep on believing",
    "-----------------------------",
    "Makesō de nakisō de",
    "Kiete shimai sō na boku wa",
    "Dare no kotoba wo shinji arukeba ii no",
    "Ā makenaide nakanaide",
    "Kiete shimai sō na toki wa",
    "Jibun no koe wo shinji arukeba ii no",
    "Itsunotokidomo kanashimi mo",
    "Sakete wa torenai keredo",
    "Egao wo misete ima wo ikite yukō",
    "Ima wo ikite yukō",
    "-----------------------------",
    "Haikei, kono tegami yonde iru anata ga",
    "Shiawase na koto wo negaimasu",]