name: unit-test-action
run-name: ${{ github.actor }} triggered automated unit test run
on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - 'master'
jobs:
  unit-test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      - run: npm install
      - run: npm run test
